### ISSUE TITLE
[SAVE] Parties cursor observe added handler is called twice when a new Party is created

### ISSUE THREAD

**Issue by leoj3n** [pkaushik/parties#1]
To reproduce:
1. Run the application, http://chicago-parties.meteor.com
2. Open console
3. You should see "added: [some id]" printed for every party in the Parties collection
4. Create a new party
5. See the "added: [some id]" log message called twice (instead of once as expected) with two different id values

---

(you;d need to log in with your github account to create a party)

**Comment by pkaushik** [comment]
Don't see this in the latest version.
