### ISSUE TITLE
callback URL for github

### ISSUE THREAD

**Issue by 0xbs0d** [pkaushik/parties#4]
Hi,

I'm trying to test this app. I built a new app on github but can't seem to manage to set my callback URL right. Can you help me out? Tnx.

**Comment by PracticalCode** [comment]
In the [`\server\accounts.js`] file, you'll find the following code sections:

```
// chicago-parties.meteor.com
// ServiceConfiguration.configurations.insert({
  // service: "github",
  // clientId: "5c9b7e93a5830dd3634a",
  // secret: "1fd43cfe0e0311e726e239a7a1bec03f8c3c2c89"
// });

// localhost:3000
ServiceConfiguration.configurations.insert({
  service: "github",
  clientId: "83f1c796a14e1f6ea61a",
  secret: "1c59890a41679554964713050e237ee89332731b"
});
```

As you'll be able to see, when you compare it to the current [`42755c9  on Oct 31, 2015`] GitHub version; I've uncommented the [`localhost`] version & commented the [`chicago-parties.meteor.com`] version.

In addition, for the provided GitHub keys above for OAuth to work, you must actually use [`http://localhost:3000/`] for your Meteor Test app & not a local IP [`10.10.10.13`].

**_Note_**:  I recommend you make the "localhost" the default in the GitHub repository; considering that the hosted [`chicago-parties.meteor.com`] version is currently defunct/offline.  In addition, this information from this comment should be included in the [`README.md`] file.

**Comment by 0xbs0d** [comment]
I'm sorry, my bad. I understand your code and I got how it works. What I'm asking is something else. Here, on github in the OAuth Application Settings, at the bottom, you need to set up a URL for your app. 
My current url is http://IP_ADDRESS/_oauth/github?storeAndClose
But that doesn't seem to work. Your app works just great on localhost but I have problems deploying the example somewhere. That's all :) Sorry for the misunderstanding.

**Comment by PracticalCode** [comment]
I'm not sure if GitHub OAuth will work with an [`IP_ADDRESS`] vs a [`URL`] ... also, this might help:
- [GitHub OAuth API Documentation  --  https://developer.github.com/v3/oauth/#redirect-urls](https://developer.github.com/v3/oauth/#redirect-urls)

Are you using a [`URL`]?...  i.e.  [`http://www.MyCoolDomain.com/MyCoolApp`]

... vs an IP address...  i.e.  [`http://8.8.8.8/MyCoolApp`]

**Comment by 0xbs0d** [comment]
I'm using and IP so maybe that's why it's not working...
Thank you I'll check this out. That might be it! Tnx again :)
